# Generated by Django 5.1.7 on 2026-03-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_nit_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
