# Generated by Django 5.1.7 on 2026-03-25 00:57

import django.db.models.deletion
from django.db import migrations, models


def copy_locations_from_producers(apps, schema_editor):
    """Copy departamentos and municipios from producers tables to locations tables,
    preserving IDs so existing FK values in producers_productor remain valid."""
    ProducersDepartamento = apps.get_model('producers', 'Departamento')
    ProducersMunicipio = apps.get_model('producers', 'Municipio')
    LocationsDepartamento = apps.get_model('locations', 'Departamento')
    LocationsMunicipio = apps.get_model('locations', 'Municipio')

    for dep in ProducersDepartamento.objects.all():
        LocationsDepartamento.objects.get_or_create(
            id_departamento=dep.id_departamento,
            defaults={'nombre': dep.nombre},
        )

    for mun in ProducersMunicipio.objects.all():
        loc_dep = LocationsDepartamento.objects.get(id_departamento=mun.id_departamento_id)
        LocationsMunicipio.objects.get_or_create(
            id_municipio=mun.id_municipio,
            defaults={'nombre': mun.nombre, 'id_departamento': loc_dep},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("producers", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(copy_locations_from_producers, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="municipio",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="municipio",
            name="id_departamento",
        ),
        migrations.AlterField(
            model_name="productor",
            name="id_municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productores",
                to="locations.municipio",
                verbose_name="Ubicación (Municipio)",
            ),
        ),
        migrations.DeleteModel(
            name="Departamento",
        ),
        migrations.DeleteModel(
            name="Municipio",
        ),
    ]
