# Generated by Django 5.1.7 on 2026-09-17 03:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('locations', '0001_initial'),
        ('productores', '0004_alter_productor_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle de Pedido', 'verbose_name_plural': 'Detalles de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Envío', 'verbose_name_plural': 'Envíos'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='envio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='telefono',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='id_envio',
            field=models.ForeignKey(blank=True, help_text='Grupo de envío (productor + origen) que despacha esta línea.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='commerce.envio'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='nombre_producto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='peso_unitario_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='requiere_frio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envio',
            name='empaque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envio',
            name='entrega_dias_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='entrega_dias_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='envio',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envio',
            name='id_municipio_origen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='envios_origen', to='locations.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='id_productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='productores.productor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='jerarquia',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envio',
            name='kilos_adicionales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envio',
            name='neveras',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envio',
            name='peso_bruto_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='envio',
            name='peso_facturable_kg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='envio',
            name='peso_frio_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='envio',
            name='sobreflete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envio',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envio',
            name='total_grupo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='envio',
            name='trayecto_aplicado',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='envio',
            name='valor_kilo_adicional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='envio',
            name='valor_kilo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pago',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado_payu',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='firma_valida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pago',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pago',
            name='order_id_payu',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pago',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='referencia_payu',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_documento',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_nombre',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprador_tipo_documento',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='departamento_destino_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empaque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_dias_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega_dias_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_municipio_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='locations.municipio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='pedido',
            name='municipio_destino_nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pedido',
            name='sobreflete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('preparación', 'Preparación'), ('camino', 'Camino'), ('entregado', 'Entregado')], default='preparación', max_length=255),
        ),
        migrations.AlterField(
            model_name='envio',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='commerce.pedido'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pago',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
