# Generated by Django 5.1.7 on 2026-03-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id_departamento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                ("id_municipio", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                (
                    "id_departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipios",
                        to="locations.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "ordering": ["id_departamento__nombre", "nombre"],
                "unique_together": {("id_departamento", "nombre")},
            },
        ),
    ]
