# Generated by Django 5.1.7 on 2026-09-04 03:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id_trayecto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('urbano', 'Urbano'), ('zonal', 'Zonal'), ('nacional', 'Nacional'), ('territorial', 'Territorial'), ('especial', 'Especial')], max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('jerarquia', models.PositiveSmallIntegerField(help_text='Mayor jerarquía gana cuando origen y destino difieren.', unique=True, verbose_name='Jerarquía')),
                ('valor_kilo_inicial', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor kilo inicial')),
                ('valor_kilo_adicional', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor kilo adicional')),
                ('sobreflete_minimo', models.DecimalField(decimal_places=2, default=Decimal('800.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Sobreflete mínimo')),
                ('porcentaje_sobreflete', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Fracción sobre el subtotal del grupo. 0.0200 = 2%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Porcentaje de sobreflete')),
                ('cobrar_kilo_adicional_en_1kg', models.BooleanField(default=False, help_text='Replica el comportamiento del tarifario original, que factura un kilo adicional cuando el peso facturable es exactamente 1 kg.', verbose_name='Cobrar kilo adicional en envíos de 1 kg')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trayecto',
                'verbose_name_plural': 'Trayectos',
                'ordering': ['jerarquia'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpaque',
            fields=[
                ('id_configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('capacidad_kg', models.DecimalField(decimal_places=3, default=Decimal('6.000'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Capacidad por nevera (kg)')),
                ('costo_nevera', models.DecimalField(decimal_places=2, default=Decimal('12000.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo por nevera')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de empaque',
                'verbose_name_plural': 'Configuración de empaque',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='empaque_configuracion_unica_activa')],
            },
        ),
        migrations.CreateModel(
            name='PromocionEnvio',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('umbral_subtotal', models.DecimalField(decimal_places=2, default=Decimal('200000.00'), help_text='Subtotal de productos a partir del cual se cubre el envío.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Umbral de subtotal')),
                ('jerarquia_maxima_cubierta', models.PositiveSmallIntegerField(blank=True, help_text='Vacío: cubre cualquier destino. 2: sólo urbano y zonal.', null=True, verbose_name='Jerarquía máxima cubierta')),
                ('tope_cubierto', models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: sin tope.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tope cubierto')),
                ('cubre_sobreflete', models.BooleanField(default=True, verbose_name='Cubre el sobreflete')),
                ('cubre_empaque', models.BooleanField(default=False, verbose_name='Cubre el empaque refrigerado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoción de envío',
                'verbose_name_plural': 'Promociones de envío',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('activo',), name='promocion_envio_unica_activa')],
            },
        ),
        migrations.CreateModel(
            name='CoberturaMunicipio',
            fields=[
                ('id_cobertura', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(blank=True, default='', max_length=100, verbose_name='Provincia')),
                ('distancia_km_tunja', models.DecimalField(blank=True, decimal_places=2, help_text='Informativa, no interviene en el cálculo.', max_digits=7, null=True, verbose_name='Distancia a Tunja (km)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cobertura', to='locations.municipio', verbose_name='Municipio')),
                ('trayecto_destino', models.ForeignKey(blank=True, help_text='Vacío: el municipio no aparece como destino en el checkout.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coberturas_destino', to='shipping.trayecto', verbose_name='Trayecto como destino')),
                ('trayecto_origen', models.ForeignKey(blank=True, help_text='Vacío: no se despacha mercancía desde este municipio.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coberturas_origen', to='shipping.trayecto', verbose_name='Trayecto como origen')),
            ],
            options={
                'verbose_name': 'Cobertura de municipio',
                'verbose_name_plural': 'Cobertura de municipios',
                'ordering': ['municipio__id_departamento__nombre', 'municipio__nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('trayecto_origen__isnull', False), ('trayecto_destino__isnull', False), _connector='OR'), name='cobertura_al_menos_un_trayecto')],
            },
        ),
    ]
