# Generated by Django 5.1.7 on 2026-09-28 15:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_datos_dias_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionempaque',
            name='costo_nevera',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='OBSOLETO: el empaque va incluido en el flete y no se cobra. El cálculo ya no lo lee; la columna se elimina en el próximo release.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo por nevera'),
        ),
        migrations.AlterField(
            model_name='promocionenvio',
            name='cubre_empaque',
            field=models.BooleanField(default=False, help_text='OBSOLETO: el empaque ya no se cobra. El cálculo ya no lo lee; la columna se elimina en el próximo release.', verbose_name='Cubre el empaque refrigerado'),
        ),
    ]
