# Generated by Django 5.1.7 on 2025-08-17 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("revisión", "Revisión"),
                        ],
                        default="Revisión",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagenProducto",
            fields=[
                ("id_imagen", models.AutoField(primary_key=True, serialize=False)),
                (
                    "url_imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="productos_imagenes/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.producto",
                    ),
                ),
            ],
        ),
    ]
