# Generated by Django 5.1.7 on 2026-01-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('Lb', 'Libras (Lb)'), ('Kg', 'Kilogramos (Kg)'), ('Un', 'Unidad (Un)'), ('Paq', 'Paquete (Paq)'), ('Gr', 'Gramos (Gr)'), ('Oz', 'Onzas (Oz)'), ('Lt', 'Litros (Lt)'), ('Ml', 'Mililitros (Ml)')], default='Un', max_length=10),
        ),
    ]
