# Generated by Django 5.1.7 on 2026-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producto_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('Lb', 'Libras (Lb)'), ('Kg', 'Kilogramos (Kg)'), ('Un', 'Unidad (Un)'), ('Paq', 'Paquete (Paq x12)'), ('Gr', 'Gramos (Gr)'), ('Oz', 'Onzas (Oz)'), ('Lt', 'Litros (Lt)'), ('Ml', 'Mililitros (Ml)')], default='Un', max_length=10),
        ),
    ]
