# Generated by Django 5.1.7 on 2026-03-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='es_promocionado',
            field=models.BooleanField(default=False, verbose_name='Promocionado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Porcentaje de Descuento (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('Lb', 'Libras (Lb)'), ('Kg', 'Kilogramos (Kg)'), ('Un', 'Unidad (Un)'), ('Paq', 'Paquete (Paq x12)'), ('Gr', 'Gramos (Gr)'), ('Oz', 'Onzas (Oz)'), ('Lt', 'Litros (Lt)'), ('Ml', 'Mililitros (Ml)')], default='Un', max_length=10),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='products.departamento')),
            ],
            options={
                'ordering': ['id_departamento__nombre', 'nombre'],
                'unique_together': {('id_departamento', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='id_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='products.municipio'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
