# Generated by Django 5.1.7 on 2026-03-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_departamento_producto_es_promocionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_presentacion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 200 para 200 g, 1.5 para 1.5 L. Opcional.', max_digits=10, null=True, verbose_name='Cantidad por presentación'),
        ),
    ]
