# Generated by Django 5.1.7 on 2026-01-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_departamento_remove_producto_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_promocionado',
            field=models.BooleanField(default=False, verbose_name='Promocionado'),
        ),
    ]
