# Generated by Django 5.1.7 on 2026-01-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producto_es_promocionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Porcentaje de Descuento (%)'),
        ),
    ]
