# Generated by Django 5.1.7 on 2026-03-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_producto_cantidad_presentacion"),
        ("products", "0006_producto_porcentaje_descuento"),
    ]

    operations = []
