# Generated by Django 5.1.7 on 2026-03-25 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_locations_from_products(apps, schema_editor):
    """Copy departamentos and municipios from products tables to locations tables,
    preserving IDs so existing FK values in products_producto remain valid."""
    ProductsDepartamento = apps.get_model('products', 'Departamento')
    ProductsMunicipio = apps.get_model('products', 'Municipio')
    LocationsDepartamento = apps.get_model('locations', 'Departamento')
    LocationsMunicipio = apps.get_model('locations', 'Municipio')

    for dep in ProductsDepartamento.objects.all():
        LocationsDepartamento.objects.get_or_create(
            id_departamento=dep.id_departamento,
            defaults={'nombre': dep.nombre},
        )

    for mun in ProductsMunicipio.objects.all():
        loc_dep = LocationsDepartamento.objects.get(id_departamento=mun.id_departamento_id)
        LocationsMunicipio.objects.get_or_create(
            id_municipio=mun.id_municipio,
            defaults={'nombre': mun.nombre, 'id_departamento': loc_dep},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("producers", "0002_remove_municipio_id_departamento_and_more"),
        ("products", "0007_merge_20260325_0057"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(copy_locations_from_products, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="municipio",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="municipio",
            name="id_departamento",
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="locations.municipio",
            ),
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="imagenproducto",
            options={
                "verbose_name": "Imagen de Producto",
                "verbose_name_plural": "Imágenes de Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="imagenproducto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("aprobado", "Aprobado"),
                    ("rechazado", "Rechazado"),
                    ("revisión", "Revisión"),
                ],
                default="revisión",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id_post", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("revisión", "Revisión"),
                        ],
                        default="revisión",
                        max_length=10,
                    ),
                ),
                ("mensaje", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "id_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.categoria",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Departamento",
        ),
        migrations.DeleteModel(
            name="Municipio",
        ),
    ]
