# Generated by Django 5.1.7 on 2026-09-04 03:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_municipio_id_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='requiere_frio',
            field=models.BooleanField(default=False, help_text='Default para los productos de la categoría. Cada producto puede sobreescribirlo.', verbose_name='Requiere cadena de frío'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso real de despacho con empaque. Sin él el producto no se puede cotizar.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Peso de despacho (kg)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_frio_override',
            field=models.BooleanField(blank=True, default=None, help_text='Vacío: hereda de la categoría.', null=True, verbose_name='Cadena de frío (override)'),
        ),
    ]
