# Generated by Django 5.1.7 on 2026-09-04 03:50
# Sincroniza el esquema con campos de modelo que nunca se migraron (url_imagen quedó en
# varchar(100) mientras el modelo declara 500). Sólo metadatos en Postgres.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_peso_y_cadena_de_frio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='url_imagen',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='productos_imagenes/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('revisión', 'Revisión')], default='revisión', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(choices=[('Lb', 'Libras (Lb)'), ('Kg', 'Kilogramos (Kg)'), ('Un', 'Unidad (Un)'), ('Paq', 'Paquete (Paq x12)'), ('Gr', 'Gramos (Gr)'), ('Oz', 'Onzas (Oz)'), ('Lt', 'Litros (Lt)'), ('Ml', 'Mililitros (Ml)'), ('Dz', 'Docena (Dz)'), ('Bt', 'Botella (Cm3)')], default='Un', max_length=10),
        ),
    ]
